FROM caddy:alpine

WORKDIR /usr/share/caddy

COPY ./GameExport/ .

CMD ["caddy", "file-server", "--domain", "46.101.127.20.sslip.io", "--header", "Cross-Origin-Opener-Policy: same-origin", "--header", "Cross-Origin-Embedder-Policy: require-corp"]