FROM nginx:stable-alpine

WORKDIR /usr/share/nginx/html

COPY ./GameExport/ .

RUN printf 'server {\n\
    listen 80;\n\
    location / {\n\
        root /usr/share/nginx/html;\n\
        index index.html;\n\
        try_files $uri $uri/ /index.html;\n\
        add_header Cross-Origin-Opener-Policy same-origin;\n\
        add_header Cross-Origin-Embedder-Policy require-corp;\n\
    }\n\
}' > /etc/nginx/conf.d/default.conf

EXPOSE 80