version: '3.8'

services:
  frontend:
    image: caddy:alpine
    ports:
      - "80:80"
      - "443:443"
      - "8001:8001"
    volumes:
      - ./GameExport:/usr/share/caddy
      - ./CaddyFile:/etc/caddy/Caddyfile
    restart: always

  matchmaker:
    build: 
      context: ./backend/matchmaker
      dockerfile: Dockerfile_matchmaker
    expose:
      - "8001"
    environment:
      - SERVER_IP=46.101.127.20
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always