services:
  frontend:
    image: caddy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./GameExport:/usr/share/caddy
      - ./CaddyFile:/etc/caddy/Caddyfile
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - caddy_net
    restart: always

  matchmaker:
    build:
      context: ./backend/matchmaker
      dockerfile: Dockerfile_matchmaker
    networks:
      - caddy_net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

networks:
  caddy_net:
    driver: bridge